package com.myy803.traineeship_project.domainmodel;

public enum Interest {

	WEB_DEVELOPMENT("WEB_DEVELOPMENT"),
	MOBILE_DEVELOPMENT("MOBILE_DEVELOPMENT"),
	DATA_SCIENCE("DATA_SCIENCE"),
	MACHINE_LEARNING("MACHINE_LEARNING"),
	ARTIFICIAL_INTELLIGENCE("ARTIFICIAL_INTELLIGENCE"),
	CLOUD_INFRASTRUCTURE("CLOUD_INFRASTRUCTURE"),
	CYBERSECURITY("CYBERSECURITY"),
	EMBEDDED_SYSTEMS("EMBEDDED_SYSTEMS"),
	GAME_DEVELOPMENT("GAME_DEVELOPMENT"),
	SOFTWARE_ENGINEERING("SOFTWARE_ENGINEERING"),
	DEVOPS("DEVOPS"),
	DATABASE_MANAGEMENT("DATABASE_MANAGEMENT"),
	UI_UX_DESIGN("UI_UX_DESIGN"),
	NETWORKING("NETWORKING"),
	BUSINESS_ANALYSIS("BUSINESS_ANALYSIS"),
	PROJECT_MANAGEMENT("PROJECT_MANAGEMENT"),
	IOT("IOT"),
	BLOCKCHAIN("BLOCKCHAIN"),
	ROBOTICS("ROBOTICS"),
	AR_VR("AR_VR");
	
	private final String value;
	
	private Interest(String value) {
		this.value = value;
	}
	
	public String getValue() {
		return value;
	}
}
